# Generated by Django 5.1 on 2024-09-09 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EXE', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userName',
            new_name='user_name',
        ),
    ]
