# Generated by Django 5.1.5 on 2025-01-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXE', '0002_rename_username_comment_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tittle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
