# Generated by Django 5.1.5 on 2025-01-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXE', '0004_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
