# Generated by Django 5.1.5 on 2025-01-30 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXE', '0005_comment_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
